# Generated by Django 3.2 on 2021-04-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameNo', models.AutoField(primary_key=True, serialize=False)),
                ('gameName', models.CharField(max_length=50, verbose_name="game's name")),
                ('gameInfo', models.TextField()),
                ('gamePrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gameGenre', models.CharField(max_length=50, verbose_name="game's price")),
                ('gameDeveloper', models.CharField(max_length=50, verbose_name="game's developer")),
                ('gameReleaseDate', models.DateField()),
            ],
        ),
    ]
